version: '3.8'

networks:
  net_app:
    driver: bridge
  net_db:
    driver: bridge

services:
  app:
    build: .
    depends_on:
      - database
      - cache
      - dbpgsql
    networks:
      - net_app
      - net_db
    ports:
      - "8082:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
# enable volumes for development php source codes.
# disable volumes for confirming content inside the container based on Dockerfile.
    # volumes:
    #   - ./laravel-8.5.5:/var/www/html      

  database:
    image: percona:5.7
    # platform: linux/amd64
    networks:
      - net_db
    restart: always
    healthcheck:
      test: mysqlshow -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 3s
      retries: 10
    volumes:
      - db_data-8.5.5-laravel:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33062:3306"

  cache:
    image: redis:6.0
    networks:
      - net_db
    restart: always
    ports:
      - "63792:6379"
  
  #PostgreSQL Service
  dbpgsql:
    image: postgres:12.0-alpine
    networks:
      - net_db
    container_name: dbpgsql
    working_dir: /data/pgsql
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d    
    environment:
      - "POSTGRES_MULTIPLE_DATABASES=wakka_db,nuxt"
      - "POSTGRES_USER:postgres"
      - "POSTGRES_PASSWORD:CS}5>AQ@Xlxe9=>d"

    ports:
      - 5433:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080

volumes:
  db_data-8.5.5-laravel:
